### PR TITLE
add dropped group after batch.reset

### PR DESCRIPTION
**Pull request by cjw85**
Python batched poa sample drops a group when batch is full.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by vellamike** [comment]
ok to test

**Comment by vellamike** [comment]
add to whitelist

**Comment by vellamike** [comment]
Thanks @cjw85 !

**Comment by vellamike** [comment]
rerun tests

**Comment by vellamike** [comment]
There appears to be some issue with GPUCI, investigating

**Comment by vellamike** [comment]
rerun tests

**Pull request merged**
