### PR TITLE
[cudamapper] Fix cmake failure.

### PR DESCRIPTION
**Pull request by rilango**
Fixes cmake error due to missing DESTINATION

### CODE REVIEW

**Comment by mimaric** [comment]
Any idea why did this pass our CI?
On my machine CMake also fails without this change

**Comment by rilango** [comment]
> Any idea why did this pass our CI?
> On my machine CMake also fails without this change

I have not yet investigated the root cause. I will investigate it.

**Comment by mimaric** [comment]
Thank! For the record, this was broken in PR #375.

@ahehn-nv I see that you introduced `cudamapper-bin` in addition to `cudamapper` target. IIUC `cudamapper` was supposed to produce the library and `cudamapper-bin` the binary.
Knowing all this `DESTINATION bin` is probably not the best fix for this problem.

This is the error I was getting:
````
CMake Error at cudamapper/CMakeLists.txt:61 (install):
  install TARGETS given no ARCHIVE DESTINATION for static library target
  "cudamapper".

**Comment by ahehn-nv** [comment]
Hm, I didn't not see this error. Anyhow, yes, it `cudamapper` is the library which should go to `lib`, while `cudamapper-bin` is the binary. #377 fixes this.

**Pull request merged**
