### PR TITLE
[ci] move style check to separate test

### PR DESCRIPTION
**Pull request by tijyojwad**

### CODE REVIEW

**Comment by vellamike** [comment]
@tijyojwad Do we know why check is failing? I'm seeing a 404 when I look at details for `gpuCI/clara-genomics-analysis/check-style`

**Comment by tijyojwad** [comment]
@vellamike it's failing because the `style-check` job doesn't pull submodules recursively. Filed a request at https://github.com/rapidsai/ops/issues/234

**Comment by mike-wendt** [comment]
rerun tests

**Comment by mike-wendt** [comment]
@vellamike @tijyojwad looks like it's failing to find the target `check-format` now

Let me know if you run into any other issues, it looks like the submodules are being handled properly now

**Comment by tijyojwad** [comment]
@mike-wendt I think the CI side of things are fine now. I forgot to initialize the environment for this test, so a few packages were missing

**Comment by tijyojwad** [comment]
@mike-wendt any idea what could be going on here? https://gpuci.gpuopenanalytics.com/blue/rest/organizations/jenkins/pipelines/gpuCI-private/pipelines/clara-genomics-analysis/pipelines/prb/pipelines/clara-genomics-analysis-style/runs/47/log/?start=0

I just got a passing job, rebased and pushed and now seeing this error log

**Comment by tijyojwad** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by tijyojwad** [comment]
@vellamike this should be good now

**Pull request merged**
