### PR TITLE
Merging dev-v0.2.0 into cudamapper-dev

### PR DESCRIPTION
**Pull request by mimaric**

### CODE REVIEW

**Comment by vellamike** [comment]
did you mean to assign this to yourself @mimaric ?

**Comment by mimaric** [comment]
Not really sure what are our rules for assigning...

**Comment by vellamike** [comment]
I'm a bit confused by this PR, if the intention is to merge dev-v0.2.0 into cudamapper-dev why merge from mimaric:cudamapper-dev ?

**Comment by mimaric** [comment]
In that case I would have to push the changes directly to `cudamapper-dev`, without any review.
@tijyojwad is that ok in this case?

**Comment by tijyojwad** [comment]
@mimaric main thing would be to run tests and validate conflicts. we can create a PR to run the automated tests and verify code looks sane, then close the PR push directly to `cudamapper-dev`

**Comment by mimaric** [comment]
Ok, closing the PR and pushing the change directly to `dev-v0.2.0`

**Pull request closed without merging**
