### PR TITLE
[cudamapper] Not copying reads which should be skipped

### PR DESCRIPTION
**Pull request by mimaric**

### CODE REVIEW

**Comment by vellamike** [comment]
Looks like there is a compilation failure on CI? 

```

[104/127] Building CXX object cudamapper/tests/CMakeFiles/cudamappertests.dir/main.cpp.o

[105/127] Building CXX object cudamapper/tests/CMakeFiles/cudamappertests.dir/Test_CudamapperIndexGeneratorGPU.cpp.o

FAILED: cudamapper/tests/CMakeFiles/cudamappertests.dir/Test_CudamapperIndexGeneratorGPU.cpp.o 

/usr/bin/g++-5   -I/usr/local/cuda/include -Icudamapper/data -I../3rdparty/bioparser/include -I../3rdparty/bioparser/vendor/zlib -I3rdparty/bioparser/vendor/zlib -I../cudamapper/include -I../common/logging/include -I../3rdparty/spdlog/include -I../common/utils/include -isystem ../3rdparty/googletest/googletest/include -isystem ../3rdparty/googletest/googletest -isystem ../3rdparty/googletest/googlemock/include -isystem ../3rdparty/googletest/googlemock -O3 -DNDEBUG   -std=gnu++1z -MD -MT cudamapper/tests/CMakeFiles/cudamappertests.dir/Test_CudamapperIndexGeneratorGPU.cpp.o -MF cudamapper/tests/CMakeFiles/cudamappertests.dir/Test_CudamapperIndexGeneratorGPU.cpp.o.d -o cudamapper/tests/CMakeFiles/cudamappertests.dir/Test_CudamapperIndexGeneratorGPU.cpp.o -c ../cudamapper/tests/Test_CudamapperIndexGeneratorGPU.cpp

../cudamapper/tests/Test_CudamapperIndexGeneratorGPU.cpp: In member function 'virtual void claragenomics::TestCudamapperIndexGeneratorGPU_CATCAAG_AAGCTA_3_5_Test::TestBody()':

../cudamapper/tests/Test_CudamapperIndexGeneratorGPU.cpp:198:52: error: could not convert 'representation_and_minimizers' from 'std::vector<std::pair<long unsigned int, std::vector<claragenomics::Minimizer> > >' to 'std::vector<unsigned int>'

```

**Comment by mimaric** [comment]
That's really weird... It reports the error on like 198 and there's only a comment on the line 198. Checking if it has something to do with the fact that that PR #83 got merged into it in the middle of testing

**Comment by mimaric** [comment]
Yes, that's the problem. Let me fix it...

**Comment by vellamike** [comment]
> Yes, that's the problem. Let me fix it...

sorry... I did think about that but I assumed our CI was smart enough to abort the build and retry.

**Comment by mimaric** [comment]
Yes, that's strange. It basically run half of test with one code (before auto-merging) and the other with another (after auto-merging)

@tijyojwad Can you have a look at this behavior of CI?

**Pull request merged**
