### PR TITLE
[cga] Smart device pointers

### PR DESCRIPTION
**Pull request by mimaric**
Added helper function which allocate device memory and pack it into a unique/smart pointer

### CODE REVIEW

**Comment by ahehn-nv** [comment]
I think we should discuss on our next meeting whether we want to manage memory using smart ptrs or have custom container-like objects (e.g. promote https://github.com/clara-genomics/ClaraGenomicsAnalysis/blob/master/cudaaligner/src/device_storage.cuh).

**Comment by tijyojwad** [comment]
@ahehn-nv @mimaric I think these utilities are generally useful to have. Custom container objects can be specific to modules that want to implement them for their use cases, so we can support both. What do you think?

and I think we can also move device_storage under `cudautils.hpp`, which could use `make_unique_cuda_malloc` in its implementation

**Comment by mimaric** [comment]
Ok, let's discuss whether we want this in our sync call. Merging it is not urgent.

**Comment by tijyojwad** [comment]
@mimaric can this be closed?

**Comment by mimaric** [comment]
Yes it can. Did the device container work get merged/moved to utils?

**Comment by ahehn-nv** [comment]
Not yet, thanks for the reminder!

**Comment by mimaric** [comment]
Closing this bug. Similar behavior will be added in PR 63

**Pull request closed without merging**
